version: "3.1"

volumes:
  mariadb:
    driver: local

networks:
  db:
    driver: bridge

services:
  php:
    build:
      context: ./
    volumes:
      - './file:/var/www/html'
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './file:/var/www/html'
      - './file/docker/nginx:/etc/nginx/conf.d'

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./my-db:/var/lib/mysql
    networks:
      db:


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    expose:
      - 8080
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    networks:
      db:

